apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
      - image: hlebauhusevichart/hello@sha256:2f7b66f3364f99964a75568afd80499cd704fb97d06e69a6f74fff892ad5639d
        name: hello
        ports:
        - containerPort: 80
          name: hello
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello
spec:
  ports:
  - name: "hello-service"
      port: 80
  selector:
    app: hello
