apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
  name: hello
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
    spec:
      containers:
      - image: hlebauhusevichart/werfhello
        name: hello
        ports:
        - containerPort: 80
          name: hello
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
  name: hello
spec:
  ports:
  - name: "hello-service"
      port: 80
  selector:
    app: hello
