name: Project Hello setup

on: 
  workflow_dispatch:
    branches:
      - main
      - dev

jobs:
  docker_push:
    
    runs-on: ubuntu-latest

    steps:    
      # Check repository
      - name: Checkout data
        uses: actions/checkout@v2
      
      #Docker steps          
      - name: Docker login
        env:
          LOGIN: ${{secrets.LOGIN}}
          PASS: ${{secrets.PASS}}
        run: |
          echo $LOGIN
          echo $PASS 
          docker login -u $LOGIN -p $PASS

